<?php
# custom/openapi/Business/OpenApiHandler.php
namespace openapi;

/**
 * OpenApiHandler - Handles OpenAPI specification generation and serving
 *
 * Provides endpoints for:
 * - /api/openapi/spec.json - OpenAPI 3.1 JSON specification
 * - /api/openapi/ui - Swagger UI interface (future)
 *
 * @package openapi
 */
class OpenApiHandler
{
    /**
     * Generate and return OpenAPI specification
     *
     * @return array OpenAPI spec and metadata
     */
    public static function generateSpec(): array
    {
        try {
            $customPath = \bX\WarmUp::$BINTELX_HOME . '../custom/';

            $generator = new \bX\OpenApiGenerator($customPath);

            // Set API metadata from environment
            $generator->setMetadata(
                'Bintelx API',
                'Auto-generated API documentation from endpoint docblock annotations. This specification is generated by scanning all endpoint files.',
                '1.0.0'
            );

            // Scan all endpoint files
            $generator->scan();

            // Generate OpenAPI spec
            $spec = $generator->generate();

            http_response_code(200);
            return [
                'success' => true,
                'message' => 'OpenAPI specification generated successfully',
                'spec' => $spec,
                'meta' => [
                    'generated_at' => date('c'),
                    'endpoints_scanned' => count($generator->getEndpoints()),
                    'paths_found' => count($spec['paths'] ?? [])
                ]
            ];

        } catch (\Exception $e) {
            \bX\Log::logError("OpenAPI generation error: " . $e->getMessage());
            http_response_code(500);
            return [
                'success' => false,
                'message' => 'Failed to generate OpenAPI specification',
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Return raw OpenAPI JSON (without wrapper)
     * This is the format that Swagger UI and other tools expect
     *
     * @return array Raw OpenAPI spec
     */
    public static function getRawSpec(): array
    {
        try {
            $customPath = \bX\WarmUp::$BINTELX_HOME . '../custom/';

            $generator = new \bX\OpenApiGenerator($customPath);

            $generator->setMetadata(
                'Bintelx API',
                'API documentation for Bintelx platform. Authentication uses JWT tokens obtained from bnxt Header,Cookie and Body.',
                '1.0.0'
            );

            $generator->scan();
            $spec = $generator->generate();

            http_response_code(200);
            return $spec;

        } catch (\Exception $e) {
            \bX\Log::logError("OpenAPI generation error: " . $e->getMessage());
            http_response_code(500);
            return [
                'openapi' => '3.1.0',
                'info' => [
                    'title' => 'Error',
                    'version' => '1.0.0',
                    'description' => 'Failed to generate spec: ' . $e->getMessage()
                ],
                'paths' => []
            ];
        }
    }

    /**
     * Serve Swagger UI HTML page
     *
     * @return array HTML content
     */
    public static function serveSwaggerUI(): array
    {
        $appUrl = \bX\Config::get('APP_URL');
        $specUrl = $appUrl . '/api/openapi/spec.json';

        $html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bintelx API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui.css" />
    <style>
        body {
            margin: 0;
            padding: 0;
        }
        .topbar {
            display: none;
        }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>

    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.10.5/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "{$specUrl}",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout",
                persistAuthorization: true,
                tryItOutEnabled: true
            });
        };
    </script>
</body>
</html>
HTML;

        http_response_code(200);
        return [
            'html' => $html
        ];
    }

    /**
     * Get statistics about the API
     *
     * @return array API statistics
     */
    public static function getStats(): array
    {
        try {
            $customPath = \bX\WarmUp::$BINTELX_HOME . '../custom/';

            $generator = new \bX\OpenApiGenerator($customPath);
            $generator->scan();
            $spec = $generator->generate();

            $endpoints = $generator->getEndpoints();

            // Count methods
            $methodCounts = [];
            $scopeCounts = ['ROUTER_SCOPE_PUBLIC' => 0, 'ROUTER_SCOPE_PRIVATE' => 0];
            $tagCounts = [];

            foreach ($endpoints as $endpoint) {
                foreach ($endpoint['methods'] as $method) {
                    $methodCounts[$method] = ($methodCounts[$method] ?? 0) + 1;
                }

                $scopeCounts[$endpoint['scope']] = ($scopeCounts[$endpoint['scope']] ?? 0) + 1;

                foreach ($endpoint['tags'] as $tag) {
                    $tagCounts[$tag] = ($tagCounts[$tag] ?? 0) + 1;
                }
            }

            http_response_code(200);
            return [
                'success' => true,
                'message' => 'API statistics retrieved successfully',
                'data' => [
                    'total_endpoints' => count($endpoints),
                    'total_paths' => count($spec['paths'] ?? []),
                    'methods' => $methodCounts,
                    'scopes' => $scopeCounts,
                    'tags' => $tagCounts,
                    'generated_at' => date('c')
                ]
            ];

        } catch (\Exception $e) {
            \bX\Log::logError("OpenAPI stats error: " . $e->getMessage());
            http_response_code(500);
            return [
                'success' => false,
                'message' => 'Failed to retrieve API statistics',
                'error' => $e->getMessage()
            ];
        }
    }
}
